# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19QYy7P3WO3gSSXdkk6itoEwcq3DW166w
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from groq import Groq
import io, fitz, re
from arabic_reshaper import reshape
from bidi.algorithm import get_display

# --- إعدادات الصفحة والهوية البصرية ---
st.set_page_config(page_title="Strategic AI Advisor | Master's Project", layout="wide")

def fix_ar(text):
    try: return get_display(reshape(str(text)))
    except: return text

# استدعاء مفتاح API من الإعدادات الآمنة (Secrets)
# في كولاب كان مكتوباً صراحة، هنا نسحبه بأمان
API_KEY = st.secrets.get("GROQ_API_KEY", "ضع_مفتاحك_هنا_للتجربة_المحلية")
client = Groq(api_key=API_KEY)

# --- تصاميم CSS مخصصة للاحترافية ---
st.markdown("""
    <style>
    .main { background-color: #f4f7f9; }
    .stCard { background: white; padding: 20px; border-radius: 15px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
    h1, h2 { color: #1e3a8a; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
    .stButton>button { border-radius: 8px; background-color: #1e3a8a; color: white; height: 3em; width: 100%; }
    </style>
    """, unsafe_allow_html=True)

# --- منطق معالجة البيانات (Caching لتحسين السرعة) ---
@st.cache_data
def analyze_document(file_bytes, file_name):
    ext = file_name.split('.')[-1].lower()
    if ext == 'pdf':
        doc = fitz.open(stream=file_bytes, filetype="pdf")
        text = " ".join([page.get_text() for page in doc])
        return text[:5000] # نأخذ عينة كافية للتحليل العميق
    else:
        df = pd.read_csv(io.BytesIO(file_bytes)) if ext == 'csv' else pd.read_excel(io.BytesIO(file_bytes))
        return df.describe().to_string()

# --- واجهة المستخدم (Sidebar) ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2103/2103633.png", width=100)
    st.title("🤖 المستشار الذكي")
    uploaded_file = st.file_uploader("ارفع وثيقة الدراسة", type=['pdf', 'csv', 'xlsx'])

    st.divider()
    st.subheader("🛠️ خيارات التحليل")
    depth = st.select_slider("عمق التقرير", options=["موجز", "متوسط", "تحليل نقدي موسع"])
    tone = st.selectbox("نبرة التقرير", ["رسمية أكاديمية", "إبداعية استشارية"])

    if st.button("توليد التقرير الاستراتيجي"):
        if uploaded_file:
            st.session_state.process = True
        else:
            st.warning("يرجى رفع ملف أولاً")

# --- الساحة الرئيسية ---
if uploaded_file and st.session_state.get('process'):
    file_bytes = uploaded_file.getvalue()
    content = analyze_document(file_bytes, uploaded_file.name)

    st.title("📊 لوحة النتائج الاستراتيجية")

    # توزيع المحتوى في ألسنة (Tabs)
    tab1, tab2, tab3 = st.tabs(["📄 التقرير الاستراتيجي", "📈 التحليل البصري", "💬 مناقشة النتائج"])

    with tab1:
        with st.spinner('يتم الآن توليد رؤى الذكاء الاصطناعي...'):
            prompt = f"أنت خبير استراتيجي. قدم تحليلاً بمستوى الماجستير (نبرة {tone}) وبعمق ({depth}). اللغة: العربية الفصحى."
            chat = client.chat.completions.create(
                messages=[{"role": "system", "content": prompt},
                          {"role": "user", "content": f"حلل الوثيقة التالية واستخرج الرؤى الأساسية: {content}"}],
                model="llama-3.3-70b-versatile"
            )
            report = chat.choices[0].message.content
            st.markdown(f'<div class="stCard">{report}</div>', unsafe_allow_html=True)
            st.download_button("📥 تحميل النص كملف", report, file_name="analysis.txt")

    with tab2:
        st.subheader("تحليل المؤشرات التفاعلية")
        # مثال لرسم تفاعلي Plotly يعكس احترافية البيانات
        col1, col2 = st.columns(2)
        with col1:
            fig1 = px.pie(names=[fix_ar('الفرص'), fix_ar('التحديات'), fix_ar('نقاط القوة')],
                          values=[40, 25, 35], hole=0.4, title=fix_ar("توزيع الثقل الاستراتيجي"))
            st.plotly_chart(fig1, use_container_width=True)
        with col2:
            fig2 = px.bar(x=[1, 2, 3, 4], y=[10, 20, 15, 25], title=fix_ar("توقعات النمو المستقبلي"))
            st.plotly_chart(fig2, use_container_width=True)

    with tab3:
        st.subheader("💬 اسأل المحلل")
        query = st.text_input("لديك استفسار حول النتائج؟")
        if query:
            st.info(f"سيتم دمج ذاكرة المحادثة هنا للإجابة على: {query}")

else:
    # واجهة الترحيب الجمالية
    st.markdown("""
        <div style='text-align: center; margin-top: 50px;'>
            <h1 style='font-size: 3em;'>Strategic Vision Platform</h1>
            <p style='font-size: 1.5em; color: #666;'>مشروع الماجستير: نظام تحليل البيانات المدعم بالذكاء الاصطناعي</p>
            <p>قم برفع الملف من القائمة الجانبية لبدء المحاكاة</p>
        </div>
    """, unsafe_allow_html=True)